[profile.default]
src = "src"
test = 'test'
script = 'script'
out = "out"
libs = ["lib"]
cache = true
cache_path = 'cache'
gas_reports = ['*']
auto_detect_solc = true
solc = "0.8.21"
verbosity = 2
block_number = 0
fork_block_number = 0
chain_id = 1
bytecode_hash = "ipfs"
build_info = true
build_info_path = "build-info"

[profile.remappings]
forge-std = "lib/forge-std"

[etherscan]
mainnet = { key = "" }

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/e94aa65f254c4e5eb1034773cc6e5018"
sepolia = "https://sepolia.infura.io/v3/e94aa65f254c4e5eb1034773cc6e5018"

[fuzz]
runs = 256
max_test_rejects = 65536

[fmt]
line_length = 150
tab_width = 4
bracket_spacing = true
trailing_comma = "always"
semi = true
single_quote = false
